### ISSUE TITLE
Where can I get token?

### ISSUE THREAD

**Issue by ntnbich0205** [lyc8503/jjwxcCrawler#1]
Where can I get token? I don't know how to get token to login. Can you help me?

**Comment by lyc8503** [comment]
由于使用的是安卓协议，只能使用抓包安卓设备上的登录请求的方式获取 Token，安卓比较常用的抓包软件可能是 Http Canary，高版本安卓抓包需要先 ROOT 手机，如果没 ROOT 的话可以尝试在模拟器上抓包。先启动抓包再在手机 APP 中重新登录一下账号，找到带有 login 字样的请求，其中包含需要的 Token。

Since the Android protocol is used, the Token can only be obtained by capturing the login request on the Android device. The commonly used packet capture software for Android may be Http Canary. Higher versions of Android need to root the phone first. If there is no ROOT, you can Try capturing packets on the emulator. Start the packet capture first, then re-login the account in the mobile APP, and find the request with the word login, which contains the required Token.
